First Push
JDGonzal/psl-workshop-api-testing-js pull request #1
Opened 2017-09-22 21:27 UTC by JDGonzal

2017-09-22 21:29 UTC, JDGonzal commented
Taller, parte 1

2017-09-22 21:35 UTC, germandavid85 requested changes

2017-09-22 21:35 UTC, germandavid85 commented on test/HelloWorld.test.js
> +	describe( '#indexOf()' , () => {
cambiar a 2 espacios de indentación

2017-09-22 21:35 UTC, germandavid85 commented on test/HelloWorld.test.js
> +		assert.equal(-1, [1,2,3].indexOf(4));
corregir indentación

2017-09-22 21:35 UTC, germandavid85 commented on test/HelloWorld.test.js
> +});
adicionar linea en blanco

2017-09-22 21:55 UTC, germandavid85 approved these changes

2017-09-24 16:33 UTC, aperdomob reviewed
Falta agregar la licencia

2017-09-25 13:57 UTC, jhenaoz approved these changes

2017-09-25 16:42 UTC, merged