MyFirstApiConsume.test.js, Before to run install
JDGonzal/psl-workshop-api-testing-js pull request #2
Opened 2017-09-25 21:41 UTC by JDGonzal

npm install --save-dev http-status-codes
npm install --save superagent superagent-promise

2017-09-25 22:37 UTC, aperdomob requested changes

2017-09-25 22:37 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +});
los it van dentro de los describes

2017-09-25 23:54 UTC, germandavid85 requested changes

2017-09-25 23:54 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +     const query = {
corregir indentación

2017-09-25 23:54 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +     const query = {
corregir indentación

2017-09-25 23:54 UTC, germandavid85 commented on test/MyFirstApiConsume.test.js
> +     const query = {
corregir indentación

2017-09-25 23:55 UTC, aperdomob approved these changes

2017-09-26 00:03 UTC, germandavid85 approved these changes

2017-09-26 00:04 UTC, merged