Integración Continua,
JDGonzal/psl-workshop-api-testing-js pull request #3
Opened 2017-09-26 20:00 UTC by JDGonzal

Requerido para "Travis CI" https://travis-ci.org. Pág 6 del taller

2017-09-26 20:35 UTC, germandavid85 requested changes

2017-09-26 20:35 UTC, germandavid85 commented on .travis.yml
> +	- /^v\d+\.\d+\.\d+$/
adicionar linea en blanco al final del archivo

2017-09-26 20:53 UTC, aperdomob approved these changes

2017-09-26 20:57 UTC, germandavid85 approved these changes

2017-09-26 23:10 UTC, aperdomob requested changes
Revisa el travis como fue construido porque la integración continua dice que tiene errores

2017-09-27 15:55 UTC, aperdomob approved these changes

2017-09-27 16:13 UTC, merged